### ISSUE TITLE
PvP is terrible!

### ISSUE THREAD

**Issue by MonoAdrian23** [alvin0319/AntiHack#1]
PvP is terrible with this plugin.
Cps 5.0 but it doesnt work.
Cps 0.6 or lower and it doesnt work.
Latest Version
Pocketmine 3.12.2

**Comment by orest-code** [comment]
:0

**Comment by alvin0319** [comment]
closes in https://github.com/alvin0319/AntiHack/commit/1749e24ce6eadb58974f231237b3bf977f3b1c32
